config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'

  resources :agencies

  resources :clients do
    resources :campaigns
  end

  resources :campaigns do
    resources :ads
  end

  resources :sessions, only: [:new, :create, :destroy]

  get '/login', to: 'sessions#new'

  get '/logout', to: 'sessions#destroy'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :campaign

  # has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :clients
  has_secure_password
  has_many :campaigns, through: :clients

  # has_many :ads, through: :campaigns
  def is_client?
    self.has_attribute? :point_of_contact
  end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :client
  has_many :ads, dependent: :destroy
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :agency
  has_many :campaigns, dependent: :destroy
  has_secure_password

  def is_client?
    self.has_attribute? :point_of_contact
  end

end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

  def index
    @ads = Ad.all
  end

  def new
    @campaign  = Campaign.find(params[:campaign_id]) #current campaign
    @ad        = @campaign.ads.new #create new ad
  end

  def create
    @campaign  = Campaign.find(params[:campaign_id]) #current campaign
    @ad        = @campaign.ads.new(ads_params)
    if @ad.save
      redirect_to campaign_path(params[:campaign_id])
    else
      render 'new'
    end
  end

  def edit
    @ad        = Ad.find(params[:ad_id])
  end

  def show
    @ad        = Ad.find(params[:id])
    @campaign  = @ad.campaign
    @client    = @ad.campaign.client
  end

  def destroy
    @ad        = Ad.find(params[:id])
    @ad.destroy
    redirect_to camapaign_ads_path
  end

private
  def ads_params
    params.require(:ad).permit(:html_file, :width, :height, :image)

  end

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  def new
    @agency = Agency.new
  end

  def create
    @agency = Agency.new(agency_params)
    if @agency.save
      session[:agency_id] = @agency.id
      flash[:notice] = 'You have successfully signed up'
      redirect_to clients_path
    else
      render 'new'
  end
end

private
  def agency_params
    params.require(:agency).permit(:business_name, :founded_date, :password, :password_confirmation)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :is_client?, :is_agency?

  private

    def current_user
      if session[:client]
        @current_user ||= Client.find_by(id: session[:user_id]) if session[:user_id]
      else
        @current_user ||= Agency.find_by(id: session[:user_id]) if session[:user_id]
      end
    end

    def is_client?
      !session[:client].nil?
    end

    def is_agency?
      !session[:agency].nil?

    end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  def index
    @campaigns = current_user.campaigns
  end


  def show
    @campaign = Campaign.find(params[:id])
    @client   = @campaign.client
    @ads      = @campaign.ads
  end

  def new
    @client   = Client.find(params[:client_id]) #current_user
    @campaign = @client.campaigns.new #make new campaign
    @ad       = @campaign.ads.new #make new ad
  end

  def create
    @client   = Client.find(params[:client_id])
    @campaign = Campaign.new
    @campaign.client = @client
    @campaign.launch_date = DateTime.strptime(params[:campaign][:launch_date], "%m/%d/%Y")
    @campaign.campaign_name = params[:campaign][:campaign_name]
    if @campaign.save
      redirect_to client_path(params[:client_id])
    else
      render 'new'
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])
    params[:campaign][:launch_date] = DateTime.strptime(params[:campaign][:launch_date], "%m/%d/%Y")
    if @campaign.update_attributes(campaign_params)
      redirect_to client_path(@campaign.client_id)
    else
      render 'edit'
    end
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy
    redirect_to client_path(params[:client_id])
  end

private
  def campaign_params
    params.require(:campaign).permit(:campaign_name, :launch_date)

  end



end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client   = Client.find(params[:id])
    @campaigns = @client.campaigns
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new client_params
    if @client.save
      redirect_to clients_path, notice: "Client was created!"
    else
      render 'new'
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(client_params)
      redirect_to clients_path
    else
      render 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_path
  end

private
  def client_params
    params.require(:client).permit(:business_name, :point_of_contact, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    agency = Agency.find_by(business_name: params[:business_name])
    if agency && agency.authenticate(params[:password])
      session[:user_id] = agency.id
      session[:agency] = true
      session[:client] = nil
      redirect_to clients_path, notice: 'Logged in!'
    else
      client = Client.find_by(business_name: params[:business_name])
      if client && client.authenticate(params[:password])
        session[:user_id] = client.id
        session[:agency] = nil
        session[:client] = true
        redirect_to campaigns_path, notice: 'Logged in!'
      else
        flash.now.alert = 'Invalid login, try again'
        render 'new'
      end
    end

  end

  def destroy
    session[:user_id] = nil
    session[:agency] = nil
    session[:client] = nil
    redirect_to welcome_index_path, notice: 'Logged out!'
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/ad_helper.rb
module AdHelper
end

app/helpers/agency_helper.rb
module AgencyHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_helper.rb
module CampaignHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ads/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
<h1>Edit Ad</h1>
<%= form_for [@campaign, @ad ], html: { multipart: true } do |f| %>
<% if @ad.errors.any? %>
<div class="error_message">
  <h2>Form is invalid</h2>
  <ul>
    <% for message in @ad.errors.full_messages %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :image %>
  <%= f.file_field :image %>
</div>

<div class="field">
  <%= f.label :width %>
  <%= f.text_field :width %>
</div>

<div class="field">
  <%= f.label :height %>
  <%= f.text_field :height %>
</div>

<div class="action"><%= f.submit %></div>

<% end %>
</div>

app/views/ads/new.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <h1>Create New Ad</h1>
    <%= bootstrap_form_for [@campaign, @ad ], html: { multipart: true } do |f| %>
    <% if @ad.errors.any? %>
      <div class="error_message">
      <h2>Form is invalid</h2>
        <ul>
        <% for message in @ad.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
    <%= f. text_field :html_file %>
    </div>
    <div class="field">
    <%= f.text_field :width %>
    </div>
    <div class="field">
    <%= f.text_field :height %>
    </div>

    <div class="action"><%= f.submit %></div>

    <% end %>
</div>

app/views/ads/show.html.erb
<iframe src="<%= @ad.html_file %>" width="<%= @ad.width %>" height="<%= @ad.height %>"></iframe>

app/views/agencies/create.html.erb
<h1>Agency#create</h1>
 <p>
  <%= link_to 'Sign Up', new_agency_path %>
 </p>

app/views/agencies/new.html.erb
<h1>Sign Up</h1>
<%= form_for @agency do |f| %>
<% if @agency.errors.any? %>
<div class="error_message">
  <h2>Form is invalid</h2>
  <ul>
    <% for message in @agency.errors.full_messages %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :business_name %>
  <%= f.text_field :business_name %>
</div>

<div class="field">
  <%= f.label :founded_date %>
  <%= f.text_field :founded_date %>
</div>

<div class="field" >
  <%= f.label :pasword %>
  <%= f.password_field :password %>
</div>

<div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

<div class="actions"><%= f.submit %></div>

<% end %>

app/views/campaigns/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <h1>Edit Campaign</h1>
  <%= bootstrap_form_for [@client, @campaign] do |f| %>
  <% if @campaign.errors.any? %>
    <div class="error_message">
      <h2>Form is invalid</h2>
        <ul>
          <% for message in @campaign.errors.full_messages %>
          <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :campaign_name %>
  </div>
  <div class="field">
    <%= f.text_field :launch_date, "data-provide" => "datepicker" %>
  </div>

  <div class="actions"><%= f.submit %></div>

<% end %>
</div>

app/views/campaigns/index.html.erb
<div class="container-fluid">
<h1>Campaigns</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Campaign Name</th>
      <th>Launch Date</th>
    </tr>
  </thead>
  <% @campaigns.each do |campaign| %>
  <tbody>
    <td><%= link_to campaign.campaign_name, campaign_path(campaign.id) %></td>
    <td><%= campaign.launch_date %></td>
  <% end %>
  </tbody>
</table>

<% if current_user && is_agency? %>
  <%= link_to 'Create New Campaign', new_campaign_path %>
<% else %>
  <%= link_to 'Back', welcome_index_path %>
<% end %>
</div>

app/views/campaigns/new.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <h1>Create New Campaign</h1>
  <%= bootstrap_form_for [@client, @campaign] do |f| %>
  <% if @campaign.errors.any? %>
    <div class="error_message">
      <h2>Form is invalid</h2>
        <ul>
        <% for message in @campaign.errors.full_messages %>
        <li><%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :campaign_name %>
  </div>
  <div class="field">
    <%= f.text_field :launch_date, "data-provide" => "datepicker" %>
  </div>
  <div class="actions"><%= f.submit %></div>
  <div class="actions">
    <%= link_to "Back", clients_path, class: "btn-outline-primary" %>
  </div>
  <% end %>

</div>

app/views/campaigns/show.html.erb
<div class="container-fluid">
  <h2><%= @campaign.campaign_name %></h2>
  <p><%= @campaign.launch_date %></p>

<% if current_user && is_agency? %>
  <%= link_to "Create Ad", new_campaign_ad_path(@campaign) %><br>
<% else %>
  <%= link_to 'Back', campaigns_path %>
<% end %>
  <div class="container">
    <table class="table table-hover">
    <thead>
      <tr>
        <th>Html Link</th>
        <th>Size</th>
        <th>Tools</th>
      </tr>
    </thead>
  <% @ads.each do |ad| %>
    <tbody>
      <tr>
        <td>
          <%= link_to ad.html_file, campaign_ad_path(@campaign, ad) %>
        </td>
        <td>
          <%= ad.width %>x<%= ad.height %>
        </td>
      <% if current_user && is_agency? %>
        <td>
          <%= link_to "Delete", campaign_path(@campaign, ad),
            method: :delete,
            data: { confirm: "Are you sure you want to delete ad? "} %>
        </td>
      <% else %>
        <td colspan="2"></td>
      </tr>
    </tbody><br>
      <% end %>
  <% end %>
  </table>
  </div>
</div>

  <% if current_user && is_agency? %>
    <br><%= link_to "Back", clients_path(@client), class: "btn-outline-primary" %>
  <% end %>

app/views/clients/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
<h1>Edit Client</h1>
<%= bootstrap_form_for @client do |f| %>
<% if @client.errors.any? %>
<div class="error_message">
  <h2>Form is invalid</h2>
  <ul>
    <% for message in @client.errors.full_messages %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%#= f.label :business_name %>
  <%= f.text_field :business_name %>
</div>

<div class="field">
  <%#= f.label :point_of_contact %>
  <%= f.text_field :point_of_contact %>
</div>

<div class="field" >
  <%#= f.label :pasword %>
  <%= f.password_field :password %>
</div>

<div class="field">
  <%#= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

<div class="actions"><%= f.submit %></div>

<%= link_to "Back", clients_path, class:"btn btn-outline-primary" %>


<% end %>
</div>

app/views/clients/index.html.erb
<div class="container-fluid">
<h1>Clients</h1>

<%= link_to 'Create New Client', new_client_path %>

<div class="container-fluid">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Client</th>
        <th>Point of Contact</th>
        <th>Tools</th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
      <tr>
        <th>
          <%= link_to client.business_name, client_path(client.id) %>
        </th>
        <th>
          <%= client.point_of_contact %>
        </th>
        <th>
          <%= link_to "Edit", edit_client_path(client.id) %>
          <%= link_to "Delete", client_path(client.id), method: :delete,
          data: {confirm: " Are you sure you want to delete #{client.business_name}?"} %>
        </th>
      </tr>
    </tbody>
      <% end %>
  </table>


</div>

app/views/clients/new.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
<h1>Create New Client</h1>
  <%= bootstrap_form_for @client do |f| %>
  <% if @client.errors.any? %>
  <div class="error_message">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @client.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.text_field :business_name %>
  </div>

  <div class="field">
    <%= f.text_field :point_of_contact %>
  </div>

  <div class="field" >
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions"><%= f.submit %></div>

  <%= link_to "Back", clients_path, class:"btn btn-outline-primary" %>
  <% end %>
</div>

app/views/clients/show.html.erb
<div class="container-fluid">
  <h3>Client: <%= @client.business_name %></h3>
  <h4>Point of Contact: <%= @client.point_of_contact %></h4>

  <h3>Campaigns</h3>

  <% if current_user && is_agency? %>
    <%= link_to "Create New Campaign", new_client_campaign_path(@client), class: "btn btn-outline-primary"  %><br>
  <% end %>
  <div class="container-fluid">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Campaign Name</th>
          <th>Launch Date</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @campaigns.each do |campaign| %>
        <td>
          <%= link_to campaign.campaign_name,
          campaign_path(campaign.id) %>
        </td>
        <td>
          <%= campaign.launch_date.strftime("%-m/%-d/%Y") %>
        </td>
        <% if current_user && is_agency? %>
        <td>
          <%= link_to "Edit", edit_client_campaign_path(@client, campaign.id), class: "btn btn-outline-primary" %>
          <%= link_to "Delete", client_campaign_path(@client, campaign.id), class: "btn btn-outline-danger",
            method: :delete,
            data: { confirm: "Are you sure you want to delete #{campaign.campaign_name}? "} %>
        </td>
      </tbody>
  </div>
        <% else %>
          <td colpan="2"></td>
        <% end %>
        <% end %>
  </div>
  <%= link_to "Back", clients_path, class: "btn btn-outline-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
  <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css">
</head>
<body id="page-top">

<!-- Fixed navbar -->

<% if !current_user %>
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu
            </button>
            <% if current_user %>
              <li><%= link_to "Logout", logout_path, class: "navbar-brand page-scroll" %></li>
            <% else %>
              <li><%= link_to "Login", login_path, class: "navbar-brand page-scroll" %></li>
            <% end %>
        </div>
        <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="#welcome/index">Home</a></li>
                <li><a class="page-scroll" href="#about">About</a></li>
                <li><a class="page-scroll" href="#contact">Contact</a></li>
            </ul>
        </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
</nav><!-- /.navbar -->
<!-- check to see whether user is a client or agency -->
<!-- nav bar for client view -->
<% elsif current_user && is_client? %>
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu
            </button>
            <a id="brand" class="navbar-brand" href="#welcome/index">Ad Agency</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><%= link_to "Home", campaigns_path %></li>
                <li><%= link_to "Campaigns", campaigns_path %></li>
                <li><%= link_to "Logout", logout_path %></li>
            </ul>
        </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
</nav><!-- /.navbar -->
  <p>Welcome, <%= current_user.business_name %>!</p>

<!-- navbar for agency view -->
<% elsif current_user && is_agency? %>
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu
            </button>
            <a id="brand" class="navbar-brand" href="#welcome/index">Ad Agency</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><%= link_to "Home", clients_path %></li>
                <li><%= link_to "Clients", clients_path %></li>
                 <li><%= link_to "Logout", logout_path %></li>
            </ul>
        </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
</nav><!-- /.navbar -->

<div><p>Welcome, <%= current_user.business_name %>!</p></div>
<% else %>

  <!-- <nav>You're not logged in</nav> -->

<% end %>

<%= yield %>

    <!-- Theme JavaScript -->
</body>
</html>

app/views/welcome/index.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1 id="homeHeading">A Premier Digital Agency </h1>
            <hr>
            <p></p>
        </div>
    </div>

</header>


<section class="bg-primary" id="about">
  <div class="container-fluid">
    <div class="row"></div>
      <div class="col-lg-8 col-lg-offset-2 text-center"></div>
        <h2 class="section-heading">About Us</h2>
        <hr class="light">
        <p class="text-faded">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Nulla in ante nulla. Pellentesque pulvinar, nisi at dignissim consequat,
        mauris ante aliquet ligula, aliquam scelerisque magna enim in ex.
        Curabitur sed congue nisi. Cras blandit blandit sapien congue egestas.
        Nunc varius imperdiet aliquet. Nulla semper, sem id pretium tincidunt,
        nulla leo bibendum massa, imperdiet porta odio ex vel nunc.
        Quisque non nulla viverra, condimentum nisl sit amet, luctus ex. </p>

        <p>Cras rhoncus mi leo, nec accumsan mi egestas sed. Donec eu risus dui.
        Mauris ullamcorper metus vel condimentum vulputate. In interdum eleifend risus,
        ut ultrices ipsum iaculis eget. Integer iaculis purus facilisis auctor congue.
        Ut orci metus, mattis vel lectus nec, accumsan commodo est. Nunc quis rutrum erat,
        vel ultricies urna. Maecenas et eros eget leo convallis elementum non at tortor.
        Nunc sit amet metus ac nulla fringilla auctor. Proin sagittis nunc id ipsum congue,
        eu dignissim urna sodales.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Nulla in ante nulla. Pellentesque pulvinar, nisi at dignissim consequat,
        mauris ante aliquet ligula, aliquam scelerisque magna enim in ex.
        Curabitur sed congue nisi. Cras blandit blandit sapien congue egestas.
        Nunc varius imperdiet aliquet. Nulla semper, sem id pretium tincidunt,
        nulla leo bibendum massa, imperdiet porta odio ex vel nunc.
        Quisque non nulla viverra, condimentum nisl sit amet, luctus ex. </p>

        <p>Cras rhoncus mi leo, nec accumsan mi egestas sed. Donec eu risus dui.
        Mauris ullamcorper metus vel condimentum vulputate. In interdum eleifend risus,
        ut ultrices ipsum iaculis eget. Integer iaculis purus facilisis auctor congue.
        Ut orci metus, mattis vel lectus nec, accumsan commodo est. Nunc quis rutrum erat,
        vel ultricies urna. Maecenas et eros eget leo convallis elementum non at tortor.
        Nunc sit amet metus ac nulla fringilla auctor. Proin sagittis nunc id ipsum congue,
        eu dignissim urna sodales.</p>
      </div>
</section>

<section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Chat!</h2>
                    <hr class="primary">
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:contact@AdAgency.com">contact@AdAgency.com</a></p>
                </div>
            </div>
        </div>
    </section>